### ISSUE TITLE
Issue with script! Any clue?

### ISSUE THREAD

**Issue by tonymgh** [techandme/wordpress-vm#20]
Hi techandme.  So I just downloaded and installed the wordpress VM OVA, and Installed in in my ESXi server.  The script runs great, until I get to "For better security, change the system user password for []".  And I press any key, and it runs in an endless circle with the output "passwd user [] does not exist" continuously.  Take a look at the screen shots.  Then, I tried to load the wordpress site on my page and it just hangs. Banner says "just another wordpress site" then a white page on my browser. Nothing else.  Wordpress just doesn't work at all. Attached are the resources. I mean I gave it plenty of resources.  Any clue? Take a look at the screenshots.  I'm using VMware ESXi.  My networking is fine, my DNS forward/reverse works great. My NTP is fine. firewall is wide open. I'm at a loss. 
<img width="1070" alt="right before the loop - error user name" src="https://user-images.githubusercontent.com/27783466/37806642-7efb79dc-2e17-11e8-85ea-584401000a39.png">
<img width="1246" alt="resources" src="https://user-images.githubusercontent.com/27783466/37806646-8542f1c6-2e17-11e8-9352-bf66976f3001.png">
<img width="1057" alt="endless loop" src="https://user-images.githubusercontent.com/27783466/37806651-889a33d4-2e17-11e8-93ad-a0abf1bbf4ac.png">

**Comment by enoch85** [comment]
Thanks for reporting! Will have a look at this .

**Comment by enoch85** [comment]
@tonymgh  Would you mind testing if the issue is the same if you run directly from the script and implement this in the stasrtup-script: https://github.com/nextcloud/vm/blob/master/nextcloud-startup-script.sh#L411-L420

**Comment by enoch85** [comment]
This is now fixed

**Comment by tonymgh** [comment]
Awesome!  Where do I get the update?
