### ISSUE TITLE
Installation Wordpress VM (OVA)

### ISSUE THREAD

**Issue by maurerdom** [techandme/wordpress-vm#34]
Hi Techandme

I am trying to install your fantastic WordPress VM on my VMM. Everything ist going fine until he is trying to activate SSL (Let's encrypt).
The output is like this:
"We will now test that everything is ok
Press any key to continue…
Job for nginx.service failed because the control process exited with error code.
…
Couldn't load new config, reverted to old settings. Self-signed SLL is OK!

Can you perhaps tell me what is going wrong here?

**Comment by enoch85** [comment]
This issue is now resolved. Sorry to keep you waiting and THANK YOU for reporting. :)
