### ISSUE TITLE
script error

### ISSUE THREAD

**Issue by mycanaletto** [techandme/wordpress-vm#46]
Hi,

I have this error : 
![image](https://user-images.githubusercontent.com/45459269/54207132-eb6ea600-44d9-11e9-810a-e7aff498ec38.png)

Any ideas ? Merci beaucoup

lionel

**Comment by enoch85** [comment]
Thanks! 

Yeah, will release a new version today.

**Comment by enoch85** [comment]
This is now fixed with the latest release. Please download and try again. Thanks!

**Comment by mycanaletto** [comment]
Hi,

Thanks. I just restart the VM and same problem...

**Comment by enoch85** [comment]
You have to download the **new** VM. The old one still contains the old scripts.

**Comment by mycanaletto** [comment]
Downloaded and reinstalled, but new error : 

![image](https://user-images.githubusercontent.com/45459269/54302723-ba69a080-45c1-11e9-9bc9-16f135016394.png)

**Comment by enoch85** [comment]
Where was this in the script? I tested it before I released it and everything worked. Please be more precise. Just saying "it doens't work" doesn't help me much when debugging.

Thanks!

**Comment by mycanaletto** [comment]
This screenshoot is after the setup script, but at the firsts start of the VM and tt the boot Nginx dont start...

**Comment by enoch85** [comment]
OK, so:
- Did you install SSL?
- Did you install any apps?
- Decribe if you made any other changes other than default.

Thanks!

**Comment by enoch85** [comment]
I tested it several times yesterday and it worked. 

Please use the **latest** VM that was released a few days ago.

**Comment by mycanaletto** [comment]
Hi,
I am in travel. I retest when I return in my office. Thanks for your support.

Regards, lionel

**Comment by mycanaletto** [comment]
New try from scratch (deploy on ESX 6). (2 tests on private or public IP, network green online) No apps, no ssl, nginx dont start.

**Comment by enoch85** [comment]
OK, it works for me on all the systems I've tried (3 of them) and there are no issues.

If you need support installing you are always welcome to buy support in the shop: https://shop.hanssonit.se/product/premium-support-per-30-minutes/

**Comment by mycanaletto** [comment]
OK I have installed a Bitnami WP VM and is work fine.

Thanks, for support
