### ISSUE TITLE
Wordpress vm not working

### ISSUE THREAD

**Issue by dannykellett** [techandme/wordpress-vm#56]
Error: Error establishing a database connection.
Sorry but something went wrong. Please report this issue to https://github.com/techandme/wordpress-vm/issues and include the output of the error message. Thank you!
sudo -u www-data /usr/local/bin/wp option update siteurl --path=/var/www/html/wordpress failed

**Comment by enoch85** [comment]
Hmm, OK, can you please give the 

## Steps to reproduce

1.
2.
3.
4.
5. ...

Thanks!

**Comment by enoch85** [comment]
Hi again, 

I just run the VM and there where no errors.
