### ISSUE TITLE
Keyboard in image set to sweden

### ISSUE THREAD

**Issue by ThomasWalker01** [techandme/wordpress-vm#66]
Hi the Wordpress_VM_www.hanssonit.se-disk1.vhdx image has the keyboard set to sweden.
Makes it very hard to type in commands if that not where you are from :-)
Could you run the dpkg-reconfigure keyboard-configuration or something to help on startup ?

Thomas

**Comment by enoch85** [comment]
It's documented: https://docs.hanssonit.se/s/W6fMouPiqQz3_Mog/virtual-machines-vm/d/W7jILePiqQz3_Msw/wordpress-vm?currentPageId=W7jILePiqQz3_Ms3

It also happens here: https://github.com/techandme/wordpress-vm/blob/master/wordpress-startup-script.sh#L232

But sure, it could be improved. I just never find the time to attend to this project. :/

**Comment by enoch85** [comment]
I'm working on a major update in https://github.com/techandme/wordpress-vm/pull/64# right now, where this will be fixed.

**Comment by enoch85** [comment]
This should be fixed.

Please try the latest VM and report back if it didn't work.

Thanks!
