### ISSUE TITLE
wordpress script complains no network configured

### ISSUE THREAD

**Issue by ThomasWalker01** [techandme/wordpress-vm#68]
Script runs just after logon but fails with the no network present message.
Just after testing if network is OK (has local address 127.0.0.53?)

![image](https://user-images.githubusercontent.com/70429528/91632614-5f31a500-ea25-11ea-9e69-22213a3c0b32.png)
![image](https://user-images.githubusercontent.com/70429528/91632696-e121ce00-ea25-11ea-9fc8-ad5ab84b612c.png)
(Also This image does not display where to report error to:)

Yet I can connect successfully.
![image](https://user-images.githubusercontent.com/70429528/91632578-0a8e2a00-ea25-11ea-940d-eb16dc719f9b.png)
sudo apt update && sudo apt upgrade
works ok!

**Comment by enoch85** [comment]
I plan to improve the whole VM ALOT when I find the time. 

Basically copy the Nextcloud VM stuff over here which I know works great, and customize it for Wordpress. It takes time though, something I don't have right now. :/

**Comment by enoch85** [comment]
I'm working on a major update in https://github.com/techandme/wordpress-vm/pull/64# right now, where this will be fixed.

**Comment by enoch85** [comment]
This should be fixed.

Please try the latest VM and report back if it didn't work.

Thanks!
