### ISSUE TITLE
Issue with Network connection

### ISSUE THREAD

**Issue by tashielb** [techandme/wordpress-vm#79]
I have setup the Hyper-V as per instructed, both manually on version 9.0  as well as using the command to setup version 5.0 and then mapped the VHDX, however in both instances, the ubuntu does not connect to the internet, after I enter my public IP details.

**Comment by enoch85** [comment]
Hi,

I wrote an answer to your email. Please check that.

Thanks!

**Comment by apisysde** [comment]
I had the same problem with the wordpress VM under virtual box. With NAT I got into the net, with network bridge not. The error is that the configuration script does not take the input for the default gateway, so you have to do it manually.

Log in as user wordpress with password wordpress, then as root with password wordpress.
Cancel the configuration menu.
You should then end up in the command line as root.

**root@wordpress:~#**  

Go to the directory **/etc/netplan**
**root@wordpress:~# cd /etc/netplan**

View files
**root@wordpress:/etc/netplan# ls -lisa**

In my case, the network configuration is in the file **01-netcfg.yaml**
Open this with an editor:
**root@wordpress:/etc/netplan# vi 01-netcfg.yaml**

Here you can see that the entry for the gateway is missing.
Press i to enter insert mode, use the cursor keys to go to **Gateway4:**, enter the correct address for the default gateway.

Exit the input mode with the **[Escape]** key and save the file with **:wq** and **[Enter]** and exit the editor.

Now apply the new network configuration:
**root@wordpress:/etc/netplan# netplan apply**

After restarting the vm, the network connection should work.

**Comment by enoch85** [comment]
VirtualBox isn't great with networking. 

I also recommend you to use Bridged mode. That's how the VM is designed.

**Comment by enoch85** [comment]
Wrong repo...
