### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by montchr** [techandme/wordpress-vm#82]
While this code is open source, there is no obvious indication of license. Without a license, it’s unclear to others whether the code here can be modified or redistributed.

Perhaps that indicates the copyright holder is okay to any form of usage — but that would be an unfair and unsafe assumption to make. Therefore, the only safe assumption is that it should not be copied or redistributed in any way. 

Could you please add a `LICENSE` file to the repo root to establish terms of use?

**Comment by enoch85** [comment]
Thanks, this is now sorted.
