### ISSUE TITLE
No text editor installed

### ISSUE THREAD

**Issue by kinsher** [techandme/wordpress-vm#85]
The Ubuntu VM doesn't have any usable text editor. Both Nano and VIM aren't available for use. I tried installing one but get an error.

**Comment by enoch85** [comment]
`sudo apt update && sudo apt install nano`

That's the command. We don't control Ubuntu or do anything fancy with it.

**Comment by enoch85** [comment]
This is now done in the upcoming release: https://github.com/techandme/wordpress-vm/commit/4598805f482dd94e2a41fdd04ef3aea78b08ddb4
