### ISSUE TITLE
changing MARIADB root password failed

### ISSUE THREAD

**Issue by masc-mad** [techandme/wordpress-vm#91]
Hi,
after changing keyboard and timezone (german) the initial script failed with an error:

bash /var/scripts/change_db_pass.sh failed

what's wrong?

**Comment by enoch85** [comment]
Hi,

Thanks for posting.

It's impossible to answer without more information. Do you have any more output? Maybe try not changing to German and see if it helps?

**Comment by masc-mad** [comment]
Hi, 
I wasn't able to find more information, cause in the shell it only says "bash /var/scripts/change_db_pass.sh failed" 
However not changing keyboard layout to german worked
